TD-56 Proforma Entries, Add, Edit, View, List UI
vernienamca/FAIS.Web pull request #50
Opened 2024-03-11 05:53 UTC by arvinmybusybee

TD-56 Proforma Entries, Add, Edit, View, List UI

2024-03-11 06:30 UTC, rayrosure1188 requested changes
Kindly remove unnecessary spaces to avoid long line of code

2024-03-11 06:30 UTC, rayrosure1188 commented on src/app/pages/apps/pro-forma-entries/pro-forma-entry.component.html
> +
Kindly  remove unnecessary spaces

2024-03-11 06:58 UTC, rayrosure1188 approved these changes

2024-03-19 09:41 UTC, ferlyncaps approved these changes

2024-03-21 06:51 UTC, merged